package client

import (
	"crypto/sha256"
	"fmt"
	"strings"

	"github.com/paoloposso/wisdom/src/challenge"
	"github.com/paoloposso/wisdom/src/server"
)

func GetDataFromServer() {
	chal := server.GetChallenge()
	chal = proofOfWork(chal, chal.Prefix)
	data, err := server.GetData(chal)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(data)
	}
}

func proofOfWork(ch challenge.Challenge, prefix string) challenge.Challenge {
	nonce := int32(-1)

	for {
		nonce++
		ch.Nonce = nonce

		h := sha256.New()
		h.Write([]byte(fmt.Sprintf("%v", ch)))
		hashData := fmt.Sprintf("%x\n", h.Sum(nil))

		//print the hashes generated by the proof of work
		fmt.Println(hashData)

		if strings.HasPrefix(hashData, prefix) {
			break
		}
	}

	ch.Nonce = nonce

	return ch
}
